plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Yo\\.gemini\\antigravity\\scratch\\tierra-querida-restaurant\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Yo\\.gemini\\antigravity\\scratch\\tierra-querida-restaurant"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]